name = "moneyfast"
pages_build_output_dir = "dist/cloudflare"
compatibility_date = "2025-01-01"

[vars]
ALLOWED_ORIGINS = "https://moneyfast.pages.dev,https://moneyfast.eu.org,https://spr168.net,https://admin.spr168.net,http://127.0.0.1:8321,http://localhost:8321,http://127.0.0.1:8788,http://localhost:8788"

[[kv_namespaces]]
binding = "MONEYFAST_KV"
id = "6407542e266f4980a76542653102f62b"
